[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.0.0",
    "pyinstaller>=6.15.0",
    "pyqt6>=6.9.1",
    "requests>=2.32.5",
]
